apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tomcat-latest-secret-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/internet-ctf/secrets/tomcat-latest-flag/versions/1"
        path: "tomcat-latest-flag.txt"
