apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-tomcat
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 8080
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/chroot/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: tomcat-ghostcat-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:104fb00179d33bfe818eaff5a9ec5d7bae43ae8aa0899cf216084f70da544389
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:40d8d96d624808a656873027517478da9a5977d1012bc86e5228151ca06afeab
